# netlify.toml
[build]
  command   = "npm run build"
  publish   = ".next"            # or "out" if you're exporting static
  functions = ".netlify/functions"

# Only if you also installed the Next.js plugin; you don’t need this for a plain static + redirects site:
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect /api/* → your laptop
[[redirects]]
  from     = "/api/*"
  to       = "http://192.168.45.162:8000/:splat"
  status   = 200
  force    = true
